---
name: Alexis Meskowski
position: 
address: 
phone: "574-849-8784"
www: 
email: AlexisMeskowski@gmail.com
linkedin: AlexisMeskowski
aboutme: 
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
docname: "résumé"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE,
  message = FALSE
)

source("../scripts/install.R")

date_format <- function(start_date, end_date) {
  
  d <-
    ifelse(
      test = !is.na(start_date),
      yes = paste0(start_date, " -- ", end_date),
      no = end_date
    )
  
  return(d)
}
```

```{r get data, include=FALSE}
sheets_deauth()

url <- "https://docs.google.com/spreadsheets/d/13_4D6O7LhU1YIhRupox5naVz8TE-6Xbzj9ta5MPnXqM/edit?usp=sharing"

## Education
education <- 
  read_sheet(
    ss = url,
    sheet = "Education",
    col_types = "cccccci"
    ) %>% 
  mutate(date_range = date_format(start_date, end_date)) %>% 
  arrange(details_order)

## Work Experience
work_experience <- 
  read_sheet(
    ss = url,
    sheet = "Work Experence",
    col_types = "icccccic"
    ) %>% 
  drop_na(role_order) %>% 
  arrange(role_order, detail_order) %>% 
  mutate(date_range = date_format(start_date, end_date))

## Awards and Volunteering
awards_and_volunteering <-
  read_sheet(
    ss = url,
    sheet = "Awards and Volunteering",
    col_types = "icccccc"
    ) %>% 
  drop_na(item_order) %>% 
  arrange(item_order) %>% 
  mutate(date_range = date_format(start_date, end_date))

## Skills
skills <-
  read_sheet(
    ss = url,
    sheet = "Skills",
    col_types = "cci"
    ) %>% 
  drop_na(skill_order) %>% 
  arrange(category, skill_order) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup() %>% 
  unique()
```

# Education 

```{r}
detailed_entries(
  data = education, 
  when = date_range,
  what = degree,
  where = loc,
  with = uni,
  why = details
)
```

# Experience

```{r research}
work_experience %>% 
  detailed_entries(
    what = role,
    when = date_range,
    with = company,
    where = where,
    why = details
  )
```

# Skills

```{r}
skills %>% 
  detailed_entries(
    what = skill,
    with = category
  )
```

<!-- \pagebreak -->

# Awards and Volunteering

```{r}
awards_and_volunteering %>% 
  detailed_entries(
    what = item,
    # with = with,
    when = date_range,
    # where = where,
    # why = why
  )
```
